### ISSUE TITLE
corr.m_eff() does not check for division by zero

### ISSUE THREAD

**Issue by JanNeuendorf** [fjosw/pyerrors#108]
I just updated to the newest release and a few of my scripts broke, 
because corr.m_eff() computes corr.content[t]/corr.content[t+1] without checking if corr.content[t+1]  is zero. 
I do not know, if this is intentional, but i think it made sense the way it was before, where it set those timeslices to "none" in the effective mass.

**Comment by fjosw** [comment]
I last change to `Corr.m_eff` appears to have happened 5 months ago, what version did you use before and can you provide a minimal example for the error you are seeing?

**Comment by JanNeuendorf** [comment]
I do not know, which version the script was previously running on. I think it was the first 2.0 release. 
I have a correlator, which has values up to a certain timeslice and is then set to zero. 
So you can see, where the problem occurs. 
The error is:


m_eff=corr.m_eff(variant="cosh")
File "/usr/local/lib/python3.8/site-packages/pyerrors/correlators.py", line 631, in m_eff
newcontent.append(np.abs(find_root(self.content[t][0] / self.content[t + 1][0], root_function, guess=guess)))
File "/usr/local/lib/python3.8/site-packages/pyerrors/obs.py", line 744, in __truediv__
return derived_observable(lambda x, **kwargs: x[0] / x[1], [self, y], man_grad=[1 / y.value, - self.value / y.value ** 2])
ZeroDivisionError: float division by zero

**Comment by JanNeuendorf** [comment]
Would you mind, if i change this?

**Comment by fjosw** [comment]
Feel free to fix this. A general way including other kind of arithmetic errors might be to check for an `ArithmeticError`

```python
try:
    newcontent.append(self.content[t] / self.content[t + 1])
except ArithmeticError:
    newcontent.append(None)
```

**Comment by JanNeuendorf** [comment]
Yes, you are right, we only checked for None not for zero. So maybe something that i did to the correlator with the previous version set it to None on these timeslices, but this behaviour changed. We might never know.
