### ISSUE TITLE
Dublication in input.dobs.read_dobs

### ISSUE THREAD

**Issue by fjosw** [fjosw/pyerrors#110]
In the function `read_dobs` `content` is updated twice, once within and once after the if clause. I think lines 590 & 591 in https://github.com/fjosw/pyerrors/blob/develop/pyerrors/input/dobs.py should be removed as it is not possible to read an unzipped xml in the current version.

**Comment by s-kuberski** [comment]
Thanks for looking into these routines, I'll correct it.
