### ISSUE TITLE
Automatic windowing method fails for gapped and irregular chains

### ISSUE THREAD

**Issue by s-kuberski** [fjosw/pyerrors#123]
The automatic windowing procedure fails in cases where the Monte Carlo history is gapped, e.g., with stride 2, and on top of this contains also holes. The main reason for this behavior is that we do not expand the chain if `idl` is a `range`, but we do so, if it is a `list`. Minimal example, close to what is done in `test_gamma_method_irregular`:

```python
N = 10000
def gen_autocorrelated_array(inarr, rho):
    outarr = np.copy(inarr)
    for i in range(1, len(outarr)):
        outarr[i] = rho * outarr[i - 1] + np.sqrt(1 - rho**2) * outarr[i]
    return outarr

arr = np.random.normal(1, .2, size=N)
carr = gen_autocorrelated_array(arr, .8)
a = pe.Obs([carr], ['a'])
a.gamma_method()

arrt = [carr[i] for i in range(len(carr)) if i % 2 == 1]
idlt = [i for i in range(len(carr)) if i % 2 == 1]
for el in [int(e) for e in N * np.random.uniform(size=int(N/4))]:
    arrt = arrt[:el] + arrt[el + 1:]
    idlt = idlt[:el] + idlt[el + 1:]
at = pe.Obs([arrt], ['a'], idl=[idlt])
at.gamma_method(tau_exp=2)
at.plot_rho()
```

There are probably multiple ways to fix this behavior and I am not yet certain which one is the best. There is the possibility to determine the regular gaps based on the rho that we have calcuated via
```python
# detect holes:
            gapsize = 1
            if not all(isinstance(self.idl[r_name], range) for r_name in e_content[e_name]):
                for n in range(1, w_max):
                    if abs(self.e_rho[e_name][n]) < 1.e-13:
                        gapsize += 1
                    else:
                        break
```
before performing the automatic windowing procedure. This one would then be done via 
```python
                    # Standard automatic windowing procedure
                    tau = self.S[e_name] / np.log((2 * self.e_n_tauint[e_name][1:] + 1) / (2 * self.e_n_tauint[e_name][1:] - 1)) * gapsize
                    g_w = np.exp(- np.arange(1, w_max) / tau) - tau / np.sqrt(np.arange(1, w_max) * e_N)
                    for n in range(gapsize, w_max, gapsize):
                        if n < w_max // 2 - 2:
                            _compute_drho(n + 1)
                        if (g_w[n - gapsize] < 0 or n >= w_max - 1):
                            self.e_tauint[e_name] = self.e_n_tauint[e_name][n] * (1 + (2 * n + 1) / e_N) / (1 + 1 / e_N)  # Bias correction hep-lat/0306017 eq. (49)
                            self.e_dtauint[e_name] = self.e_n_dtauint[e_name][n]
                            self.e_dvalue[e_name] = np.sqrt(2 * self.e_tauint[e_name] * e_gamma[e_name][0] * (1 + 1 / e_N) / e_N)
                            self.e_ddvalue[e_name] = self.e_dvalue[e_name] * np.sqrt((n + 0.5) / e_N)
                            self.e_windowsize[e_name] = n
                            break
```
and the critical slowing down analysis would have to be adapted accordingly.

This detection seems to be quite stable, but I have not tested it thoroughly. It could be possible that it fails in some corner cases or that the bound would have to be adapted. Before I investigate this further, I wanted to discuss if we should somehow handle this differently.

**Comment by s-kuberski** [comment]
I have found some cases with very large autocorrelation, where this does not properly work - more investigation is needed.

**Comment by s-kuberski** [comment]
The following code snippet seems to resolve the problems:
```python
                else:
                    # Standard automatic windowing procedure
                    tau = self.S[e_name] / np.log((2 * self.e_n_tauint[e_name][gapsize::gapsize] + 1) / (2 * self.e_n_tauint[e_name][gapsize::gapsize] - 1))
                    g_w = np.exp(- np.arange(1, len(tau) + 1) / tau) - tau / np.sqrt(np.arange(1, len(tau) + 1) * e_N)
                    for n in range(1, w_max):
                        if n < w_max // 2 - 2:
                            _compute_drho(gapsize * n + gapsize)
                        if g_w[n - 1] < 0 or n >= w_max - 1:
                            n *= gapsize
                            self.e_tauint[e_name] = self.e_n_tauint[e_name][n] * (1 + (2 * n + 1) / e_N) / (1 + 1 / e_N)  # Bias correction hep-lat/0306017 eq. (49)
                            self.e_dtauint[e_name] = self.e_n_dtauint[e_name][n]
                            self.e_dvalue[e_name] = np.sqrt(2 * self.e_tauint[e_name] * e_gamma[e_name][0] * (1 + 1 / e_N) / e_N)
                            self.e_ddvalue[e_name] = self.e_dvalue[e_name] * np.sqrt((n + 0.5) / e_N)
                            self.e_windowsize[e_name] = n
                            break
```
All plots and, most importantly, the resulting error seem to be fine.

The dection of the gapsize is quite stable when the criterion in the `if` clause is a bit relaxed, say, to `1e-10 `. The `fft` should be the best method to detect the `gapsize`.

There is the general question of the unit of the window size and the autocorrelation time. Currently, we have a factor of gapsize, when we deal with regular and gapped chains. In the proposed fix, the unit for these numbers is one unit in terms of `idl` for the window size for gapped and irregular chains. The autocorrelation time however contains the implicit factor of `gapsize`. We could think of changing the output for regular chains (i.e., those with a `range` as `idl`) to have consistent estimates in terms of `MDU` or to print the `gapsize`, either determined with the new code or from the `range`s

**Comment by fjosw** [comment]
I was aware of this issue but never took the time to really dig into it. I like your solution for the modification of the windowing procedure. Maybe I am overlooking something but there might be a simpler and more stable way of obtaining the gap size directly from the idl, for example
```python
gapsize = np.min(np.diff(at.idl["a"]))
```

I see the problem related to the output but I am not sure about the best solution. Do you maybe want to open a PR with a proposal and then we can run a few test cases on the new code?

**Comment by s-kuberski** [comment]
Indeed, your solution to determine `gapsize` is much better than mine! I'll adapt my code to open a PR.
