### ISSUE TITLE
Recover tags from arrays in json output

### ISSUE THREAD

**Issue by fjosw** [fjosw/pyerrors#13]
When I write an array of Obs with different tags in a json.gz file and extract it again all Obs have the same tag which is composed from the individual tags. How about using some delimiter in this case from which the original tags can be reconstructed?

Example:
```python
import numpy as np
import pyerrors as pe

tt1 = pe.Obs([np.random.rand(100)], ['t|r1'], idl=[range(2, 202, 2)])
tt1.tag = 'f1'
tt2 = pe.Obs([np.random.rand(100)], ['t|r1'], idl=[range(2, 202, 2)])
tt2.tag = 'f2'
tt3 = pe.Obs([np.random.rand(100)], ['t|r1'], idl=[range(2, 202, 2)])
tt3.tag = 'f3'

pe.input.json.dump_to_json(np.array([tt1, tt2, tt3]), 'test', 'My testfile')

q = pe.input.json.load_json('test.json.gz')

print([o.tag for o in q])

> ['f1\nf2\nf3\n', 'f1\nf2\nf3\n', 'f1\nf2\nf3\n']
```

**Comment by s-kuberski** [comment]
I could not really think of a case, where all the Obs in an array have different tags. However, my implementation is lazy. I'll change the definition of the format such that a List of tags may (or has to?) be exported for N (N!=0) dimensional structures. It is more convenient to parse and unambiguous.
