### ISSUE TITLE
Issues with _filter_zeroes and Corr

### ISSUE THREAD

**Issue by s-kuberski** [fjosw/pyerrors#138]
I have noticed issues with `_filter_zeroes`. These appear when two observables with vastly different variances, defined on different subsets of an ensemble, are combined (e.g. by renormalizing a noisy correlator). In this case it can happen that configurations that belong only to the observable with the small variance are filtered out by chance. This is something that I did not have in mind when designing the method.
When this does happen to elements of correlators, the export to json fails because the Obs of the Corr are not defined on the same set of configurations anymore.

One can construct a case artificially:
```python 
li = [-pe.pseudo_Obs(.2, .1, 'a', samples=10) for i in range(6)]
for i in range(len(li)):
    li[i].idl['a'] = range(1, 21, 2)
b = pe.pseudo_Obs(1, 1e-11, 'a', samples=30)
c *= b
print(c[2].idl)
print(c[3].idl)
{'a': [1, 3, 5, 7, 9, 10, 11, 13, 15, 17, 19]}
{'a': [1, 3, 4, 5, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 26, 30]}
```
This is certainly a rare event but I have observed it a number of times in the past and this is quite annoying. 

A possible fix would be to remove the automatic filtering altogether and instead to put the feature in a function that may be called by the user. In this case, exact cancellations would manifest themselves as vanishing deltas and would not be filtered out anymore. I tend to think that this is better to live with than silent removals of configurations from the obs.

If we like to keep the feature, I see a number of possible improvements (use mean instead of the median in `_filter_zeroes`, lower filter_eps, ...).

**Comment by fjosw** [comment]
I guess the practical consequence of not filtering is that one carries more zeroes around in some cases without affecting the error estimate, right? I would be up for removing the filtering. This should not affect backward compatibility up to the relative precision that was filtered.

**Comment by fjosw** [comment]
Going one step further, this would make the attribute `is_merged` obsolete, right? If that is the case we could consider removing it which could result in a bit of a speed-up in some routines. But this requires more thought.

**Comment by s-kuberski** [comment]
> I guess the practical consequence of not filtering is that one carries more zeroes around in some cases without affecting the error estimate, right? 
Yes, I think this is correct. I thought it was a nice feature to remove these zeroes but the cases where one exactly cancels the contribution of a subset of configs is probably rare compared to the cases where I currently see problems.

**Comment by s-kuberski** [comment]
> Going one step further, this would make the attribute `is_merged` obsolete, right? If that is the case we could consider removing it which could result in a bit of a speed-up in some routines. But this requires more thought.

I am not sure. First of all, I think that this is a nice information to have. Of course this does not mean that we have to carry it around. If one likes to do the filtering manually, the parameter could still be used to identify the chains that need filtering.
