### ISSUE TITLE
Obs and Covobs defined on the same ensemble

### ISSUE THREAD

**Issue by fjosw** [fjosw/pyerrors#15]
I just noticed that no warning is issued when one attempts to add a standard Obs and a cov_Obs defined on the same ensemble
Example:
```python
import pyerrors as pe
covobs = pe.cov_Obs(0.5, 0.002, 'test')
my_obs = pe.pseudo_Obs(2.3, 0.2, 'test')
summed_obs = my_obs + covobs
summed_obs.gamma_method()
summed_obs.details()
```
It looks like the deltas of the standard Obs are just dropped.

**Comment by s-kuberski** [comment]
I fear that a few more of those issues might be hidden in the covobs changes (let's hope that this is not the case...). I'll fix this, an error should be raised.
