### ISSUE TITLE
Bug coming from difference in search methods in sfcf inputs

### ISSUE THREAD

**Issue by jkuhl-uni** [fjosw/pyerrors#163]
Hi,
I found a bug in the inputs, when one reads reweighting factors from openQCD and data from sfcf, it can happen, that the data is correctly sorted by replika in the openQCD ones, but not the sfcf read method, as  I haven't implemented it in PR #153 
Just wanted to make you aware of this, I'll try to fix it later this week, as I am currently working on refactoring the sfcf read method anyways.

**Comment by fjosw** [comment]
Thanks for taking care of this. Was this bug introduced in #153 or was it there already in previous releases?

**Comment by jkuhl-uni** [comment]
I think this appears due to the inconsistencies between the sorting by replika of openQCD observables introduced in PR #153 such that previous versions sorted them in the same way, just that in these cases it could happen that a replika label got mixed up in both cases.
