### ISSUE TITLE
No dobs-related functions from the input submodule can be used

### ISSUE THREAD

**Issue by JuanUrrea6** [fjosw/pyerrors#180]
### Describe the issue:

None of the dobs-related reading/writing functions that are defined in the pyerrors/input/dobs.py file are recognized when called. This might be because the corresponding __init__.py does not load dobs.py ?

### Code example:

```python
import pyerrors as pe
pe.input.dobs.read_pobs()
```

### Error message:

```shell
AttributeError                            Traceback (most recent call last)
Cell In[62], line 1
----> 1 pe.input.dobs.read_pobs()

AttributeError: module 'pyerrors.input' has no attribute 'dobs'
```

### Runtime information:

Python version: 3.10.10
pyerrors version: 2.6.0

**Comment by fjosw** [comment]
Hi @JuanUrrea6, thanks for spotting this bug! The issue will be resolved in the upcoming 2.8.0 release.
