### ISSUE TITLE
GEVP eigenvectors with errors 

### ISSUE THREAD

**Issue by JuanUrrea6** [fjosw/pyerrors#183]
Just a small comment in case it is of interest to the developers. It would be useful to be able to get the GEVP eigenvectors with errors from the GEVP() routine since these vectors can be used among other things to obtain the overlap factors that appear in the spectral decomposition of correlation functions, see e.g https://arxiv.org/abs/1004.4930 below Eq. 3, which in turn are useful for things like spin identification of states as explained in that same reference and it is important to propagate the error there. 

With the current functions available in pyerrors it is possible to calculate these vectors with errors rather straightforwardly, but if one wants to also include the sorting procedures that the GEVP() function internally uses (which might have to take into account the errors of the vectors for the determinant-based sorting) then the code might become a bit too long compared to a single function call.

**Comment by fjosw** [comment]
Hi @JuanUrrea6, thanks for opening this issue. Do you have a proposal for improving the code and including the feature you are mentioning? While I don't have a use case myself, I can see that this is useful and I am happy to review any pull request that adds this functionality.

**Comment by JuanUrrea6** [comment]
I can provide the lines of code which given a Corr object calculate the GEVP eigenvectors and eigenvalues with their corresponding errors via an intermediate Cholesky decomposition. Nonetheless these eigenpairs are sorted according to the magnitude of the eigenvalue in ascending order as per the eigh() default since I have not implemented the determinant-based sorting and until now just compared the eigenvectors that I get with the sorted ones that the GEVP() function produces to check consistency.

**Comment by fjosw** [comment]
I am a bit unsure about how to include this in the code. One way could be to add an additional keyword argument to the `Corr`GEVP` method which allows to extract the eigenvectors as `Obs` which (at least for now) would only work with the standard sorting method. Does this sound sensible? Maybe also @s-kuberski or @JanNeuendorf have opinions on this matter?

**Comment by s-kuberski** [comment]
Hi. I agree that adding this is a good idea and that a keyword for the `GEVP` function would be a nice way to include this. I think I did have an implementation of this in the past, but this was not related to the `Corr` module.

Concerning the sorting algorithm: I don't think that you have to include error propagation in the sorting algorithms as we, in contrast to other resampling methods, only have one solution for the GEVP at each time slice. Therefore, you could just go ahead with the sorting according to the mean values and use it to sort your `Obs`-values eigenvectors. I think that this could easily be implemented by checking the data type at the start of the sorting and, if `Obs` are present, use vectors of floats to sort the vectors of `Obs`. Or am I missing something here?

**Comment by fjosw** [comment]
I agree that the sorting could just be done on float versions of the vectors. Would you be willing to have a look at this and open a pull request @JuanUrrea6 ?
