### ISSUE TITLE
Numpy 1.25 breaks a few linalg functions

### ISSUE THREAD

**Issue by fjosw** [fjosw/pyerrors#191]
With the upcoming release of numpy 1.25 the return types of the functions `eigh` and `svd` change from tuple to a sublass of namedtuple which breaks the computation of the jacobian in `autograd`. This will lead to two failing tests in our ci:
```
FAILED tests/linalg_test.py::test_matrix_functions - TypeError: Can't differentiate w.r.t. type <class 'numpy.linalg.linalg.EighResult'>
FAILED tests/mpm_test.py::test_mpm - TypeError: Can't differentiate w.r.t. type <class 'numpy.linalg.linalg.SVDResult'>
```

I already opened an issue in the `autograd` repo (https://github.com/HIPS/autograd/issues/597) but did not have the time to find a fix for the problem.

For now that means that `pyerrors` is not fully compatible with `numpy>=1.25` and we should either change the requirements or add version guards for the affected functions until a solution is found.

**Comment by fjosw** [comment]
I found a way to solve the issue in `autograd` and opened a PR (https://github.com/HIPS/autograd/pull/599).

**Comment by s-kuberski** [comment]
That's great, thanks!
