### ISSUE TITLE
Duplicate data cause `gamma_method()` to fail with an unhelpful message

### ISSUE THREAD

**Issue by edbennett** [fjosw/pyerrors#214]
If an `Obs` is constructed with `idl` containing duplicate entries for a particular stream (e.g. because a correlator was measured twice due to fencepost issues in job preparation), then the `Obs` is constructed successfully, but `gamma_method()` fails with a relatively cryptic error.

Example:

```python
>>> import pyerrors as pe
>>> obs = pe.Obs([[1.2, 0.7, 1.0, 1.0, 1.4, 1.3]], ["data"], idl=[[1, 2, 3, 3, 4, 5]])
>>> obs.gamma_method()
```

Output:

```output
/opt/homebrew/Caskroom/miniconda/base/envs/su2_py311/lib/python3.11/site-packages/pyerrors/obs.py:1727: RuntimeWarning: divide by zero encountered in scalar remainder
  if not np.all([gi % gap == 0 for gi in gaps]):
/opt/homebrew/Caskroom/miniconda/base/envs/su2_py311/lib/python3.11/site-packages/pyerrors/obs.py:247: RuntimeWarning: divide by zero encountered in scalar floor_divide
  r_length.append((self.idl[r_name][-1] - self.idl[r_name][0] + 1) // gapsize)
/opt/homebrew/Caskroom/miniconda/base/envs/su2_py311/lib/python3.11/site-packages/pyerrors/obs.py:1082: RuntimeWarning: divide by zero encountered in scalar floor_divide
  ret = np.zeros((idx[-1] - idx[0] + gapsize) // gapsize)
/opt/homebrew/Caskroom/miniconda/base/envs/su2_py311/lib/python3.11/site-packages/pyerrors/obs.py:1084: RuntimeWarning: divide by zero encountered in scalar floor_divide
  ret[(idx[i] - idx[0]) // gapsize] = deltas[i]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[13], line 1
----> 1 obs.gamma_method()

File /opt/homebrew/Caskroom/miniconda/base/envs/su2_py311/lib/python3.11/site-packages/pyerrors/obs.py:256, in Obs.gamma_method(self, **kwargs)
    253 self.e_drho[e_name] = np.zeros(w_max)
    255 for r_name in e_content[e_name]:
--> 256     e_gamma[e_name] += self._calc_gamma(self.deltas[r_name], self.idl[r_name], self.shape[r_name], w_max, fft, gapsize)
    258 gamma_div = np.zeros(w_max)
    259 for r_name in e_content[e_name]:

File /opt/homebrew/Caskroom/miniconda/base/envs/su2_py311/lib/python3.11/site-packages/pyerrors/obs.py:364, in Obs._calc_gamma(self, deltas, idx, shape, w_max, fft, gapsize)
    343 """Calculate Gamma_{AA} from the deltas, which are defined on idx.
    344    idx is assumed to be a contiguous range (possibly with a stepsize != 1)
    345
   (...)
    361     are found in idx, the data is expanded.
    362 """
    363 gamma = np.zeros(w_max)
--> 364 deltas = _expand_deltas(deltas, idx, shape, gapsize)
    365 new_shape = len(deltas)
    366 if fft:

File /opt/homebrew/Caskroom/miniconda/base/envs/su2_py311/lib/python3.11/site-packages/pyerrors/obs.py:1084, in _expand_deltas(deltas, idx, shape, gapsize)
   1082 ret = np.zeros((idx[-1] - idx[0] + gapsize) // gapsize)
   1083 for i in range(shape):
-> 1084     ret[(idx[i] - idx[0]) // gapsize] = deltas[i]
   1085 return ret

IndexError: index 0 is out of bounds for axis 0 with size 0
```

It would be helpful if `pyerrors` could check for this condition and raise an exception that provides more actionable detail (e.g. `IndexError: idl contains a duplicate index 3 at positions 2 and 3`).

An alternative could be to identify that the data and index both match, and delete the duplicate (with or without a warning), but that kind of cleaning may be better left to user code.

**Comment by fjosw** [comment]
Thanks for reporting this, I guess we never thought about this case. Your first suggestion should be very simple modification. The second suggestion might lead to unexpected behaviour so I would prefer just throwing an exception but maybe @s-kuberski has a different opinion.

**Comment by s-kuberski** [comment]
Hi. Thanks for spotting this! I would consider the fact that you were able to create an `Obs` with and `idl` containing multiple occurrences of the same configuration to be a bug. In https://github.com/fjosw/pyerrors/blob/eb83ff20914c56fd3a07547d55982a0937450983/pyerrors/obs.py#L104-L107 we tried to check that the `idl` is properly sorted in ascending order. A simple change to `if np.any(dc <= 0):` or adding another test for `dc==0` with the proper error message would prevent you from creating the `Obs` in the first place.

As you say, the user has to decide what to do in such cases and I think that the proper place to do this is the creation of the `Obs`. If this solution is fine with you, I can push a fix.

**Comment by edbennett** [comment]
Thanks both! Failing to create the `Obs` at all seems the right option to me in terms of "failing early". I think a specific case with an informative error would be more useful than claiming an `Unsorted idx`.
