### ISSUE TITLE
plot_history unexpected behaviour for gapped idl

### ISSUE THREAD

**Issue by jkuhl-uni** [fjosw/pyerrors#215]
Hi,
I just noticed that, when using gapped data, `plot_history` shows the deltas that are set to 0 as well. This may result in "lines" on the (replica) mean values of the ensemble. I guess this is supposed to happen according to the rules for gapped Monte-Carlo-Chains, but maybe we could hide them in the history plots?

**Comment by s-kuberski** [comment]
Hi. You can use the keyword `expand=False` to hide the configs without data.

**Comment by jkuhl-uni** [comment]
Ah, damn, didn't see that at first glance, thanks!
