### ISSUE TITLE
Read specific interval with read_ms5_xsf()

### ISSUE THREAD

**Issue by j-bode** [fjosw/pyerrors#222]
Hi,
read_ms5_xsf() in pyerrors/input/openQCD.py reads all configs/samples from the output file. It would be nice to define start and stop values in order to read just a subinterval, e.g. 10-20 instead of all lets say 1-500.

**Comment by jkuhl-uni** [comment]
I'll close this issue, as the requested functionality was added in v2.9.0 and extended functionality was added in #224
