### ISSUE TITLE
Files keyword for multiple reps in read_sfcf

### ISSUE THREAD

**Issue by jkuhl-uni** [fjosw/pyerrors#225]
Hi there,
just wanted to make you aware (and maybe have a small discussion) about an inconsistency in the `input.sfcf.read_sfcf_multi()` and therefore also in the `input.sfcf.read_sfcfi()` method. There exists a keyword `files`, which takes a list of files to be read. I noticed, that this only works for one replica and not if you have multiple ones.
I can take care of this, and it seems not that hard to me.  I'll make a PR when I am done.  Before that, I just wanted to check in for one thing:
This functionality can be implemented either as a list of lists, or, similar to `idl` as a dict of lists.
There are arguments for both implementations in my opinion. On one hand, this kind of functionality is implemented in this function via lists of lists. On the other hand, I think it is saver to implement it via a `dict`, as one can recheck, if the files are written in the right replica.
It is possible to implement both and a third option which covers the current (false-ish) implementation, such that we do not break any backwards compatibility.

**Comment by s-kuberski** [comment]
Hi,
I don't really understand your comment concerning 'idl'. Do you mean the way this attribute is stored in an `Obs`? I think a list is fine and it is also in line with what is used for the openQCD input routines (where, of course, only one file per replicum is used).

**Comment by jkuhl-uni** [comment]
I think we are talking about the same, yes. My alternative to lists would have been to use the same structure as used in `Obs.idl`. However, I agree that this change would change the user API by quite a bit and we can discard the idea.
