### ISSUE TITLE
pyerrors does not work with the upcoming numpy 2 release

### ISSUE THREAD

**Issue by fjosw** [fjosw/pyerrors#231]
pyerrors raises multiple errors in combination with the numpy 2 release candidate
- I fixed the relevant breaking changes in autograd in the following PR https://github.com/HIPS/autograd/pull/618 
- matplotlib raises `ImportError: numpy.core.multiarray failed to import`. This should be fixed in the next release.

After the relevant changes have made it to pypi we will probably have to bump our minimal dependencies and potentially drop support for python 3.8 as it does not work with numpy 2 (EOL is 31 Oct 2024).

**Comment by s-kuberski** [comment]
Thanks a lot for anticipating this and for fixing the problems in the dependencies! I am fine with dropping python 3.8 in the future.

**Comment by fjosw** [comment]
[NumPy 2.0](https://github.com/numpy/numpy/releases/tag/v2.0.0) has now been released. With [autograd not being maintained anymore](https://github.com/HIPS/autograd) we might have to think about alternatives if my proposed changes are not included in a new release (let's see). Things that come to my mind:
- Fork autograd and maintain a numpy2 compatible version ourselves.
- Migrate to JAX.
- Include relevant code for automatic differentiation in our own code base.
- ...

Any opinions @s-kuberski @jkuhl-uni @JanNeuendorf @PiaLJP ?

**Comment by JanNeuendorf** [comment]
Maybe we should first write down all the "features" of autograd that are currently being used. What is the actual functionality that needs to be replaced?

**Comment by jkuhl-uni** [comment]
Hey  
overall, I agree with Fabian on this matter. Those are also the options I see.
I read through your PR on the autograd repo. I think that forking would be the most elegant option here, as the functionality for other users of autograd could potentially be preserved. In a perfect world, I would even go so far as to make an autograd2 with numpy>=2.0.0 as a requirement. However, as you mentioned, the maintenance of the code for upcoming releases of scipy and numpy could be significant (even though I am sure we would not be the only ones working on it and others would help out).  This does not seem practical for us, but I'd like to have a look into the autograd codebase to assess that.

If this is not assessed as a viable option by the others, I'd advocate for migrating the relevant code into pyerrors.  JAX seems to have a rather different focus and has built-in autograd only as a side-car if I read it right in their description.

Last, I want to point out, that autograd and JAX are probably not the only options, so we could also have a look at other libraries for automatic differentiation.

**Comment by jkuhl-uni** [comment]
Hey,
just FYI: while we were talking yesterday, someone else already forked the repo and incorporated @fjosw's changes. See here: https://github.com/mfschubert/autograd/pull/1.

**Comment by fjosw** [comment]
We managed to create a new autograd release that supports numpy 2 (https://github.com/HIPS/autograd/releases/tag/v1.7.0), I'm preparing a new pyerrors version that also supports numpy 2 and drops python 3.8 support (https://github.com/fjosw/pyerrors/pull/239)
