### ISSUE TITLE
Fits using migrad 1.3.3 broken

### ISSUE THREAD

**Issue by s-kuberski** [fjosw/pyerrors#27]
The fits that are performed using migrad in the test_prior_fit throw errors, when iminuit 1.3.3 is used; does this imply that there now is a requirement for the minimal version number of iminuit?:

tests/fits_test.py:291: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyerrors/fits.py:116: in least_squares
    return _prior_fit(x, y, func, priors, silent=silent, **kwargs)
pyerrors/fits.py:396: in _prior_fit
    m.migrad()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   RuntimeError: exception was raised in user function
E   User function arguments:
E       p = +0,000000
E   Original python exception in user function:
E   TypeError: 'float' object is not subscriptable
E     File "/home/simon/phd/git/pyerrors_github/pyerrors/fits.py", line 382, in chisqfunc
E       model = func(p, x)
E     File "/home/simon/phd/git/pyerrors_github/tests/fits_test.py", line 280, in f
E       return a[0] + a[1] * x

iminuit/_libiminuit.pyx:769: RuntimeError

**Comment by fjosw** [comment]
Yes, pyerrors now requires iminuit>=2, I updated the requirements in commit e213b374138c46e10998b7c7d9d9ebafea2b4265

**Comment by s-kuberski** [comment]
Ah, I did not see the change in the requirements... thanks!
