### ISSUE TITLE
linal_test fails

### ISSUE THREAD

**Issue by s-kuberski** [fjosw/pyerrors#28]
When running pytest on the current develop branch, linalg_test fails:

tests/linalg_test.py:304: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyerrors/linalg.py:283: in eig
    w = derived_observable(lambda x, **kwargs: anp.real(anp.linalg.eig(x)[0]), obs)
pyerrors/obs.py:1126: in derived_observable
    deriv = jacobian(func)(values, **kwargs)
../../../.local/lib/python3.6/site-packages/autograd/wrap_util.py:20: in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
../../../.local/lib/python3.6/site-packages/autograd/differential_operators.py:57: in jacobian
    vjp, ans = _make_vjp(fun, x)
../../../.local/lib/python3.6/site-packages/autograd/core.py:10: in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
../../../.local/lib/python3.6/site-packages/autograd/tracer.py:10: in trace
    end_box = fun(start_box)
../../../.local/lib/python3.6/site-packages/autograd/wrap_util.py:15: in unary_f
    return fun(*subargs, **kwargs)
pyerrors/linalg.py:283: in <lambda>
    w = derived_observable(lambda x, **kwargs: anp.real(anp.linalg.eig(x)[0]), obs)
../../../.local/lib/python3.6/site-packages/autograd/tracer.py:45: in f_wrapped
    node = node_constructor(ans, f_wrapped, argvals, kwargs, argnums, parents)

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <autograd.core.VJPNode object at 0x7fd135504b70>
value = (array([5.14144634, 0.55022181, 0.01581728, 0.08542992]), array([[ 0.34517284,  0.82409178, -0.39054664, -0.22181473],...   [ 0.73745352,  0.05786009,  0.5835535 ,  0.33508182],
       [ 0.535441  , -0.52066857, -0.66188194,  0.06418314]]))
fun = <function primitive.<locals>.f_wrapped at 0x7fd15acaebf8>
args = (array([[0.99286045, 0.3160893 , 1.32503081, 0.71702452],
       [0.3160893 , 0.35664052, 0.81995292, 0.67152304],
       [1.32503081, 0.81995292, 2.81293272, 2.00931819],
       [0.71702452, 0.67152304, 2.00931819, 1.63048166]]),)
kwargs = {}, parent_argnums = (0,), parents = (<autograd.core.VJPNode object at 0x7fd1357711d0>,)

    def __init__(self, value, fun, args, kwargs, parent_argnums, parents):
        self.parents = parents
        try:
            vjpmaker = primitive_vjps[fun]
        except KeyError:
            fun_name = getattr(fun, '__name__', fun)
            raise NotImplementedError("VJP of {} wrt argnums {} not defined"
>                                     .format(fun_name, parent_argnums))
E           NotImplementedError: VJP of eig wrt argnums (0,) not defined

../../../.local/lib/python3.6/site-packages/autograd/core.py:35: NotImplementedError

**Comment by fjosw** [comment]
I updated the autograd dependency to the git version of autograd in commit 1a5c3c8c29dd04f85e8bd9a780b020c0240cf7b6 which includes automatic differentiation of `np.linalg.eig` and fixed an `int` type which will be deprecated in numpy. As the version number did not change pip will not notice this change. If you use pip you can simply uninstall autograd and reinstall pyerrors to get the new version with which the tests work
```
pip uninstall autograd
pip install .
```

**Comment by s-kuberski** [comment]
Thanks, installing from git+https://github.com/HIPS/autograd.git solves the issue.
