### ISSUE TITLE
corr.dump method does not handle prange

### ISSUE THREAD

**Issue by JanNeuendorf** [fjosw/pyerrors#46]
It looks like the prange parameter does not get preserved after saving and reloading. 
This would be very important to me, but i do not want to change it myself out of fear of breaking the format.

**Comment by s-kuberski** [comment]
I would really like the format to survive in its current form..., JSON allows to write dictionaries inside the tag and/or description entries. We could also rethink the way, the padding is written to the tag and instead do something like
```python
tag = {'tag': some_tag, 'padding': [pl, pu], 'prange': [ra, rb]}
```
In this way, it would be easy to recover any kind of information, that you like to export together with the correlator.

**Comment by JanNeuendorf** [comment]
I do like this idea, because it would allow me to easily preserve other parameters i set. (Like t_0 for the GEVP for example) . The only concern i have is that now some keys are reserved for this internal functions. 
For example i would like to keep it so that corr.plateau() defaults to the prange unless specified otherwise. 
If we do this, we might enforce 1. the tag being a dictionary and 2. inform the user about keys with special meanings.

**Comment by s-kuberski** [comment]
I don't understand the problem with 'special keys'. I did not intend to have the possibility to mess around with the way the tag is written. Everything, that would be included the above format would be based on a property of the correlator class. 
If you like to store a lot of additional information together with your data, you can already do so by using the tag and/or the description. It is perfectly valid to use dictionarys instead of strings here.
However, I would still think of the change from above to make sure that all properties of the correlator class can be written and recovered. Your additional information would be within ```some_tag``` in my snippet.

**Comment by JanNeuendorf** [comment]
Okay, so it is not me, who sets the dictionary, but just the dump() method that makes it a dictionary before saving it? 


I also want to mention, how much i love the json format for this. Today i build a little API that just gives back the json for a requested object. It is really easy to fetch an obs or correlator from a remote machine. 

1. If Fabian allows the dependency on "requests", i would allow the load() functions to directly accept urls. 
2. We could have some example data on GitHub pages so you do not have to download it.

**Comment by s-kuberski** [comment]
Yes! My idea of translating the tag and the additional information to a dictionary for the export of the correlator class was intended to be hardcoded within the dump routine, such that all the properties of the class can be coherently exported and imported.
You would have the freedom to write whatever you want inside the correlator tag.

**Comment by JanNeuendorf** [comment]
Okay, that sounds great. 
Will you do it or should i try?

**Comment by fjosw** [comment]
> We could also rethink the way, the padding is written to the tag and instead do something like
> ```python
> tag = {'tag': some_tag, 'padding': [pl, pu], 'prange': [ra, rb]}
> ```
> In this way, it would be easy to recover any kind of information, that you like to export together with the correlator.

Just a note: With the patch I merged today the padding is not written into the tag anymore but reconstructed from the NaN Obs in the file. So that bit is not needed anymore.

**Comment by fjosw** [comment]
> I also want to mention, how much i love the json format for this. Today i build a little API that just gives back the json for a requested object. It is really easy to fetch an obs or correlator from a remote machine. 
> 
> 1. If Fabian allows the dependency on "requests", i would allow the load() functions to directly accept urls. 
> 2. We could have some example data on GitHub pages so you do not have to download it. 
> 

This sounds like an interesting idea but I also see a potential security issue in this. Maybe we can discuss this in our next meeting.

**Comment by s-kuberski** [comment]
> Okay, that sounds great. Will you do it or should i try?

Please go ahead and do it!
