### ISSUE TITLE
Gamma method in initialization of Corr

### ISSUE THREAD

**Issue by s-kuberski** [fjosw/pyerrors#67]
The fact that the gamma method is called each time a correlator is constructed can create a significant overhead for an analysis. When I add two correlators, the call to the gamma method makes up about 60% percent of the total time. In many cases, sevral manipulations are made to a correlator (renormalization, improvement, GEVP, normalization, ...) before the errors are needed, e.g., in a fit or a plot (if they are needed, at all).

In my opinion, it would be more reasonable to call the gamma method inside fit and plot routines (when the errors of the Obses are null) or leaving it to the user (as in the case of Obs) instead of calculating errors over and over again in an analysis.

**Comment by fjosw** [comment]
I agree with you, I am also in favor of changing this behavior. I would even say that it can be a bit dangerous to automatically call the `gamma_method` within say a fit routine as this will use the standard arguments for the `gamma_method` and overwrite any custom values for `S` or so which the user might have set before running the fit. This behavior could be confusing.

**Comment by JanNeuendorf** [comment]
I agree as well. I only did it this way to avoid having to test for this in every single function. 
If the performance cost is noticeable, it has to change.  
One has to be a little careful here. Functions might rely on accurate dvalues and might not raise an error if it is zero.

**Comment by fjosw** [comment]
Good point, hopefully our tests will catch these cases. I can take care of that today.

**Comment by s-kuberski** [comment]
Very good, thanks! (And I fully agree with your concerns regarding silent calls of the gamma method)
