### ISSUE TITLE
read_sfcf does not close opened files

### ISSUE THREAD

**Issue by fjosw** [fjosw/pyerrors#71]
When reading files with the new `read_sfcf` routine and all warnings enabled I get the following warning:

```
ResourceWarning: unclosed file <_io.TextIOWrapper name='my_file_name_n1' mode='r' encoding='UTF-8'>
```

In the past I had used context managers to avoid this problem. Another solution would be to explicitly close all files accessed by the function. Can you take a look at this @jkuhl-uni ?

**Comment by jkuhl-uni** [comment]
Hi,

of course I can. Can you tell me for which file type this problem appears? Probably compact, right ? I'll have a look at it

**Comment by fjosw** [comment]
Yes exactly, compact. In the other cases you make use of context managers which close the files automatically.

**Comment by jkuhl-uni** [comment]
Found the mistake, as written in the comment to the pull-request, it was a mistake, where the file we need to locate the correlator is not opened in a context manager. The other files are.
