### ISSUE TITLE
Ordering inside key of mesons-dict

### ISSUE THREAD

**Issue by s-kuberski** [fjosw/pyerrors#92]
The keys for the dictionary that is returned in ```read_mesons``` is constructed via
https://github.com/fjosw/pyerrors/blob/c9f65298b467cfe389bac7cccb21a4030ee51112/pyerrors/input/bdio.py#L460

I think that the sorting may be problematic if mass-derivatives are considered, since it is important to know which is the fist and which is the second quark in the correlation function. Otherwise, the matching of derivative and quark may be wrong. A change of the behavior would sort of break backwards compatibility, but I would consider this a bug, rather than a feature that is changed. 

Am I missing something @fjosw?

**Comment by fjosw** [comment]
I see the problem. I wouldn't be too concerned about backward compatibility for the input routines and as you say this could be rather considered a bug. Would you propose to just remove the `sorted`?

**Comment by s-kuberski** [comment]
I think removing ```sorted``` such that the key matches the ordering in the input and bdio file would cure the issue.
